#!/bin/sh

PROCESS=${0##*cputimebyprocess_}
case $1 in
   config)
cat <<EOM
graph_title CPU Usage by $PROCESS
graph_vlabel %CPU
graph_category system
cpu.label %CPU
cpu.type DERIVE 
cpu.min 0
EOM
exit 0;;
esac

CLOCK=`getconf CLK_TCK`
CTIME=0
#PIDS=`pidof $PROCESS`
PIDS=`pidof chrome | sed -e 's/\([0-9]*\)/\/proc\/\1\/stat/g'`
CHECK=`echo $PIDS|wc -m`
if [ $CHECK -lt 1 ]
then
        echo "cpu.value 0"
        exit
fi
CTIME=`echo $PIDS | xargs awk  '{CTIME+=$14+$15+$16+$17} END {print CTIME}'`

TIME=`echo ''|awk -v CTIME="$CTIME" -v CLOCK="$CLOCK" '{printf("%.0f",(CTIME/CLOCK)*100)}'`
echo "cpu.value $TIME"

